spring:
  application:
    name: blogging-platform-api
  data:
    mongodb:
      uri: mongodb://username123:password123@localhost:27017/blogging-platform?authSource=admin
      auto-index-creation: true
      uuid-representation: standard

server:
  port: 8083
